# Generated by Django 4.1 on 2022-08-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_message_options_message_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
    ]
